spring:
  cloud:
    stream:
      kafka:
        streams:
          binder:
            brokers: 192.168.7.35:9095/kcity
            configuration:
              default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
              default.value.serde: org.apache.kafka.common.serialization.Serdes$StringSerde